name: marimo_game
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flame: ^1.7.0
  permission_handler: 10.2.0
  flutter_secure_storage: 8.0.0
  connectivity: 3.0.6
  http: 0.13.5
  geolocator: ^9.0.2
  flutter_native_splash: ^2.2.19
  flame_bloc: ^1.8.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  flame_audio: ^2.0.2
  flame_splash_screen: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/marimo/
    - assets/images/shop/
    - assets/
    - assets/font/
    - assets/audio/music/

  fonts:
        - family: KimjungchulGothic
          fonts:
            - asset: assets/font/KimjungchulGothic/KimjungchulGothic-Light.ttf
              weight: 200
            - asset: assets/font/KimjungchulGothic/KimjungchulGothic-Regular.ttf
              weight: 300
            - asset: assets/font/KimjungchulGothic/KimjungchulGothic-Bold.ttf
              weight: 400
        - family: NeoDunggeunmoPro
          fonts:
            - asset: assets/font/NeoDunggeunmoPro-Regular.ttf
              weight: 200